### ISSUE TITLE
Ошибка в VkApiError::destruct_response (vkquick-1.0)

### ISSUE THREAD

**Issue by Moonquit** [Rhinik/vkquick#15]
## Описание
Я заметил ошибку, которая может возникать при  инициализации в [VkApiError::destruct_response](https://github.com/Rhinik/vkquick/blob/1.0/vkquick/exceptions.py#L40). Т.к питон ожидает 3 значения для распаковки, но при некоторых ошибках в API VK (в моем случае ошибка №17) приходит 4 значение (в моём случае - это `redirect_url`).

## Код:
```python
import asyncio

from vkquick import API


async def main():
    """
    Creates a post in the group (the wall is open)
    """
    api = API(
        token="some_token",
        version=5.124,
        owner="user"
    )

    await api.wall.post(
        owner_id=-group_id_with_an_open_wall,
        message="Test"
    )

asyncio.run(main())
```

## Ошибка в VkApiError::destruct_response:
```bash
 ... status_code, description, request_params = response["error"].values()
ValueError: too many values to unpack (expected 3)
```

## JSON ошибки, который присылает API VK:
```json
{
   "error":{
      "error_code":17,
      "error_msg":"Validation required: please open redirect_uri in browser",
      "request_params":[
         {
            "key":"method",
            "value":"wall.post"
         },
         {
            "key":"oauth",
            "value":"1"
         },
         {
            "key":"v",
            "value":"5.124"
         },
         {
            "key":"owner_id",
            "value":"-group_id_with_an_open_wall"
         },
         {
            "key":"message",
            "value":"Test"
         }
      ],
      "redirect_uri":"https://m.vk.com/activation?act=validate&api_hash=7005d2f15d640f3e02&hash=bb1ca97ec761fc37101"
   }
}

```
> Hash в `redirect_url` был заменён - ссылка недействительна

**Comment by Rhinik** [comment]
Оставьте пример JSON от вк, на котором валится метод

**Comment by Rhinik** [comment]
Есть еще ошибки, которые отличаются от обычной структуры на 3 ключа?

**Comment by Moonquit** [comment]
Да, вроде бы, ещё есть, но я не помню

**Comment by Rhinik** [comment]
Тогда поступим следующим образом: для объекта ошибки будут присваиваться __все__ поля из `error` (с такими же именами, как есть в приходящем JSON).

Есть ли ошибки, в которых нет `request_params`? Мне нужно знать это для построения текста исключения

**Comment by Moonquit** [comment]
Честно говоря, тоже не знаю. Вообще, мне кажется, что `request_params` в тексте ошибки лишние и захламляют вывод.

**Comment by Rhinik** [comment]
Да? И как же ты предлагаешь их показывать? По-моему, сейчас это сделано вполне красиво

А видеть их нужно. Как-никак, часть ответа от вк

**Comment by Moonquit** [comment]
Я предлагаю их вообще не показывать. Но можно создать атрибут `request_params`в классе [VkApiError](https://github.com/Rhinik/vkquick/blob/1.0/vkquick/exceptions.py#L22) и заполнять его при инициализации методом [VkApiError::destruct_response](https://github.com/Rhinik/vkquick/blob/1.0/vkquick/exceptions.py#L35). А разработчик, если ему это будет нужно, сам подёргает `request_params`:
```python
try:
    ...
except vkquick.exceptions.VkApiError as err:
    print(err.request_params)
```

**Comment by Rhinik** [comment]
Так я же их раскрашиваю и красиво в краткой форме вывожу...

**Comment by Moonquit** [comment]
За это респект) Но просто это выглядит _громоздко_

**Comment by Rhinik** [comment]
А если сделать возможность вывода в кратком/расширенном стиле через установку переменной окружения?

```
VKQUICK_SHOW_FULL_ERROR=1
```


К слову, это тема для нового issue

**Comment by Moonquit** [comment]
Не знаю, не лишнее ли это извращение...

**Comment by Rhinik** [comment]
Добавил поле `extra_fields` в классе исключения + отображение в дебаггере.
